// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static partial class MVC
{
    static readonly AdministrationClass s_Administration = new AdministrationClass();
    public static AdministrationClass Administration { get { return s_Administration; } }
    static readonly MainClass s_Main = new MainClass();
    public static MainClass Main { get { return s_Main; } }
    public static Library.Web.Controllers.AccountController Account = new Library.Web.Controllers.T4MVC_AccountController();
    public static Library.Web.Controllers.CultureController Culture = new Library.Web.Controllers.T4MVC_CultureController();
    public static Library.Web.Controllers.HomeController Home = new Library.Web.Controllers.T4MVC_HomeController();
    public static T4MVC.SharedController Shared = new T4MVC.SharedController();
}

namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class AdministrationClass
    {
        public readonly string Name = "Administration";
        public T4MVC.Administration.SharedController Shared = new T4MVC.Administration.SharedController();
    }
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class MainClass
    {
        public readonly string Name = "Main";
        public Library.Web.Areas.Main.Controllers.BooksController Books = new Library.Web.Areas.Main.Controllers.T4MVC_BooksController();
        public Library.Web.Areas.Main.Controllers.PeopleController People = new Library.Web.Areas.Main.Controllers.T4MVC_PeopleController();
        public T4MVC.Main.SharedController Shared = new T4MVC.Main.SharedController();
    }
}

namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ActionResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ViewResult : System.Web.Mvc.ViewResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ViewResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace Links
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Scripts {
        private const string URLPATH = "~/Scripts";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        public static readonly string bootstrap_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap.min.js") ? Url("bootstrap.min.js") : Url("bootstrap.js");
        public static readonly string bootstrap_min_js = Url("bootstrap.min.js");
        public static readonly string jquery_1_5_1_vsdoc_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-1.5.1-vsdoc.min.js") ? Url("jquery-1.5.1-vsdoc.min.js") : Url("jquery-1.5.1-vsdoc.js");
        public static readonly string jquery_1_5_1_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-1.5.1.min.js") ? Url("jquery-1.5.1.min.js") : Url("jquery-1.5.1.js");
        public static readonly string jquery_1_5_1_min_js = Url("jquery-1.5.1.min.js");
        public static readonly string jquery_1_9_0_vsdoc_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-1.9.0-vsdoc.min.js") ? Url("jquery-1.9.0-vsdoc.min.js") : Url("jquery-1.9.0-vsdoc.js");
        public static readonly string jquery_1_9_0_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-1.9.0.min.js") ? Url("jquery-1.9.0.min.js") : Url("jquery-1.9.0.js");
        public static readonly string jquery_1_9_0_min_js = Url("jquery-1.9.0.min.js");
        public static readonly string jquery_1_9_0_min_map = Url("jquery-1.9.0.min.map");
        public static readonly string jquery_ui_1_8_11_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-ui-1.8.11.min.js") ? Url("jquery-ui-1.8.11.min.js") : Url("jquery-ui-1.8.11.js");
        public static readonly string jquery_ui_1_8_11_min_js = Url("jquery-ui-1.8.11.min.js");
        public static readonly string jquery_unobtrusive_ajax_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.unobtrusive-ajax.min.js") ? Url("jquery.unobtrusive-ajax.min.js") : Url("jquery.unobtrusive-ajax.js");
        public static readonly string jquery_unobtrusive_ajax_min_js = Url("jquery.unobtrusive-ajax.min.js");
        public static readonly string jquery_validate_vsdoc_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate-vsdoc.min.js") ? Url("jquery.validate-vsdoc.min.js") : Url("jquery.validate-vsdoc.js");
        public static readonly string jquery_validate_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate.min.js") ? Url("jquery.validate.min.js") : Url("jquery.validate.js");
        public static readonly string jquery_validate_min_js = Url("jquery.validate.min.js");
        public static readonly string jquery_validate_unobtrusive_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate.unobtrusive.min.js") ? Url("jquery.validate.unobtrusive.min.js") : Url("jquery.validate.unobtrusive.js");
        public static readonly string jquery_validate_unobtrusive_min_js = Url("jquery.validate.unobtrusive.min.js");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class kendo {
            private const string URLPATH = "~/Scripts/kendo";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class _2014_1_318 {
                private const string URLPATH = "~/Scripts/kendo/2014.1.318";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string jquery_min_js = Url("jquery.min.js");
                public static readonly string kendo_all_vsdoc_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/kendo.all-vsdoc.min.js") ? Url("kendo.all-vsdoc.min.js") : Url("kendo.all-vsdoc.js");
                public static readonly string kendo_all_min_intellisense_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/kendo.all.min.intellisense.min.js") ? Url("kendo.all.min.intellisense.min.js") : Url("kendo.all.min.intellisense.js");
                public static readonly string kendo_all_min_js = Url("kendo.all.min.js");
                public static readonly string kendo_aspnetmvc_min_js = Url("kendo.aspnetmvc.min.js");
                public static readonly string kendo_autocomplete_min_js = Url("kendo.autocomplete.min.js");
                public static readonly string kendo_binder_min_js = Url("kendo.binder.min.js");
                public static readonly string kendo_button_min_js = Url("kendo.button.min.js");
                public static readonly string kendo_calendar_min_js = Url("kendo.calendar.min.js");
                public static readonly string kendo_colorpicker_min_js = Url("kendo.colorpicker.min.js");
                public static readonly string kendo_columnmenu_min_js = Url("kendo.columnmenu.min.js");
                public static readonly string kendo_combobox_min_js = Url("kendo.combobox.min.js");
                public static readonly string kendo_core_min_js = Url("kendo.core.min.js");
                public static readonly string kendo_data_min_js = Url("kendo.data.min.js");
                public static readonly string kendo_data_odata_min_js = Url("kendo.data.odata.min.js");
                public static readonly string kendo_data_signalr_min_js = Url("kendo.data.signalr.min.js");
                public static readonly string kendo_data_xml_min_js = Url("kendo.data.xml.min.js");
                public static readonly string kendo_dataviz_vsdoc_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/kendo.dataviz-vsdoc.min.js") ? Url("kendo.dataviz-vsdoc.min.js") : Url("kendo.dataviz-vsdoc.js");
                public static readonly string kendo_dataviz_barcode_min_js = Url("kendo.dataviz.barcode.min.js");
                public static readonly string kendo_dataviz_canvas_min_js = Url("kendo.dataviz.canvas.min.js");
                public static readonly string kendo_dataviz_chart_funnel_min_js = Url("kendo.dataviz.chart.funnel.min.js");
                public static readonly string kendo_dataviz_chart_min_js = Url("kendo.dataviz.chart.min.js");
                public static readonly string kendo_dataviz_chart_polar_min_js = Url("kendo.dataviz.chart.polar.min.js");
                public static readonly string kendo_dataviz_core_min_js = Url("kendo.dataviz.core.min.js");
                public static readonly string kendo_dataviz_diagram_min_js = Url("kendo.dataviz.diagram.min.js");
                public static readonly string kendo_dataviz_gauge_min_js = Url("kendo.dataviz.gauge.min.js");
                public static readonly string kendo_dataviz_map_min_js = Url("kendo.dataviz.map.min.js");
                public static readonly string kendo_dataviz_min_intellisense_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/kendo.dataviz.min.intellisense.min.js") ? Url("kendo.dataviz.min.intellisense.min.js") : Url("kendo.dataviz.min.intellisense.js");
                public static readonly string kendo_dataviz_min_js = Url("kendo.dataviz.min.js");
                public static readonly string kendo_dataviz_qrcode_min_js = Url("kendo.dataviz.qrcode.min.js");
                public static readonly string kendo_dataviz_sparkline_min_js = Url("kendo.dataviz.sparkline.min.js");
                public static readonly string kendo_dataviz_stock_min_js = Url("kendo.dataviz.stock.min.js");
                public static readonly string kendo_dataviz_svg_min_js = Url("kendo.dataviz.svg.min.js");
                public static readonly string kendo_dataviz_themes_min_js = Url("kendo.dataviz.themes.min.js");
                public static readonly string kendo_dataviz_vml_min_js = Url("kendo.dataviz.vml.min.js");
                public static readonly string kendo_datepicker_min_js = Url("kendo.datepicker.min.js");
                public static readonly string kendo_datetimepicker_min_js = Url("kendo.datetimepicker.min.js");
                public static readonly string kendo_draganddrop_min_js = Url("kendo.draganddrop.min.js");
                public static readonly string kendo_dropdownlist_min_js = Url("kendo.dropdownlist.min.js");
                public static readonly string kendo_editable_min_js = Url("kendo.editable.min.js");
                public static readonly string kendo_editor_min_js = Url("kendo.editor.min.js");
                public static readonly string kendo_filtermenu_min_js = Url("kendo.filtermenu.min.js");
                public static readonly string kendo_fx_min_js = Url("kendo.fx.min.js");
                public static readonly string kendo_grid_min_js = Url("kendo.grid.min.js");
                public static readonly string kendo_groupable_min_js = Url("kendo.groupable.min.js");
                public static readonly string kendo_imagebrowser_min_js = Url("kendo.imagebrowser.min.js");
                public static readonly string kendo_list_min_js = Url("kendo.list.min.js");
                public static readonly string kendo_listview_min_js = Url("kendo.listview.min.js");
                public static readonly string kendo_maskedtextbox_min_js = Url("kendo.maskedtextbox.min.js");
                public static readonly string kendo_menu_min_js = Url("kendo.menu.min.js");
                public static readonly string kendo_mobile_vsdoc_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/kendo.mobile-vsdoc.min.js") ? Url("kendo.mobile-vsdoc.min.js") : Url("kendo.mobile-vsdoc.js");
                public static readonly string kendo_mobile_actionsheet_min_js = Url("kendo.mobile.actionsheet.min.js");
                public static readonly string kendo_mobile_application_min_js = Url("kendo.mobile.application.min.js");
                public static readonly string kendo_mobile_button_min_js = Url("kendo.mobile.button.min.js");
                public static readonly string kendo_mobile_buttongroup_min_js = Url("kendo.mobile.buttongroup.min.js");
                public static readonly string kendo_mobile_drawer_min_js = Url("kendo.mobile.drawer.min.js");
                public static readonly string kendo_mobile_listview_min_js = Url("kendo.mobile.listview.min.js");
                public static readonly string kendo_mobile_loader_min_js = Url("kendo.mobile.loader.min.js");
                public static readonly string kendo_mobile_min_intellisense_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/kendo.mobile.min.intellisense.min.js") ? Url("kendo.mobile.min.intellisense.min.js") : Url("kendo.mobile.min.intellisense.js");
                public static readonly string kendo_mobile_min_js = Url("kendo.mobile.min.js");
                public static readonly string kendo_mobile_modalview_min_js = Url("kendo.mobile.modalview.min.js");
                public static readonly string kendo_mobile_navbar_min_js = Url("kendo.mobile.navbar.min.js");
                public static readonly string kendo_mobile_pane_min_js = Url("kendo.mobile.pane.min.js");
                public static readonly string kendo_mobile_popover_min_js = Url("kendo.mobile.popover.min.js");
                public static readonly string kendo_mobile_scroller_min_js = Url("kendo.mobile.scroller.min.js");
                public static readonly string kendo_mobile_scrollview_min_js = Url("kendo.mobile.scrollview.min.js");
                public static readonly string kendo_mobile_shim_min_js = Url("kendo.mobile.shim.min.js");
                public static readonly string kendo_mobile_splitview_min_js = Url("kendo.mobile.splitview.min.js");
                public static readonly string kendo_mobile_switch_min_js = Url("kendo.mobile.switch.min.js");
                public static readonly string kendo_mobile_tabstrip_min_js = Url("kendo.mobile.tabstrip.min.js");
                public static readonly string kendo_mobile_view_min_js = Url("kendo.mobile.view.min.js");
                public static readonly string kendo_multiselect_min_js = Url("kendo.multiselect.min.js");
                public static readonly string kendo_notification_min_js = Url("kendo.notification.min.js");
                public static readonly string kendo_numerictextbox_min_js = Url("kendo.numerictextbox.min.js");
                public static readonly string kendo_pager_min_js = Url("kendo.pager.min.js");
                public static readonly string kendo_panelbar_min_js = Url("kendo.panelbar.min.js");
                public static readonly string kendo_popup_min_js = Url("kendo.popup.min.js");
                public static readonly string kendo_progressbar_min_js = Url("kendo.progressbar.min.js");
                public static readonly string kendo_reorderable_min_js = Url("kendo.reorderable.min.js");
                public static readonly string kendo_resizable_min_js = Url("kendo.resizable.min.js");
                public static readonly string kendo_router_min_js = Url("kendo.router.min.js");
                public static readonly string kendo_scheduler_agendaview_min_js = Url("kendo.scheduler.agendaview.min.js");
                public static readonly string kendo_scheduler_dayview_min_js = Url("kendo.scheduler.dayview.min.js");
                public static readonly string kendo_scheduler_min_js = Url("kendo.scheduler.min.js");
                public static readonly string kendo_scheduler_monthview_min_js = Url("kendo.scheduler.monthview.min.js");
                public static readonly string kendo_scheduler_recurrence_min_js = Url("kendo.scheduler.recurrence.min.js");
                public static readonly string kendo_scheduler_view_min_js = Url("kendo.scheduler.view.min.js");
                public static readonly string kendo_selectable_min_js = Url("kendo.selectable.min.js");
                public static readonly string kendo_slider_min_js = Url("kendo.slider.min.js");
                public static readonly string kendo_sortable_min_js = Url("kendo.sortable.min.js");
                public static readonly string kendo_splitter_min_js = Url("kendo.splitter.min.js");
                public static readonly string kendo_tabstrip_min_js = Url("kendo.tabstrip.min.js");
                public static readonly string kendo_timepicker_min_js = Url("kendo.timepicker.min.js");
                public static readonly string kendo_timezones_min_js = Url("kendo.timezones.min.js");
                public static readonly string kendo_tooltip_min_js = Url("kendo.tooltip.min.js");
                public static readonly string kendo_touch_min_js = Url("kendo.touch.min.js");
                public static readonly string kendo_treeview_min_js = Url("kendo.treeview.min.js");
                public static readonly string kendo_upload_min_js = Url("kendo.upload.min.js");
                public static readonly string kendo_userevents_min_js = Url("kendo.userevents.min.js");
                public static readonly string kendo_validator_min_js = Url("kendo.validator.min.js");
                public static readonly string kendo_view_min_js = Url("kendo.view.min.js");
                public static readonly string kendo_web_vsdoc_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/kendo.web-vsdoc.min.js") ? Url("kendo.web-vsdoc.min.js") : Url("kendo.web-vsdoc.js");
                public static readonly string kendo_web_min_intellisense_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/kendo.web.min.intellisense.min.js") ? Url("kendo.web.min.intellisense.min.js") : Url("kendo.web.min.intellisense.js");
                public static readonly string kendo_web_min_js = Url("kendo.web.min.js");
                public static readonly string kendo_window_min_js = Url("kendo.window.min.js");
            }
        
        }
    
        public static readonly string kendo_culture_ru_RU_min_js = Url("kendo.culture.ru-RU.min.js");
        public static readonly string kendo_modernizr_custom_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/kendo.modernizr.custom.min.js") ? Url("kendo.modernizr.custom.min.js") : Url("kendo.modernizr.custom.js");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Library {
            private const string URLPATH = "~/Scripts/Library";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class People {
                private const string URLPATH = "~/Scripts/Library/People";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string Edit_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Edit.min.js") ? Url("Edit.min.js") : Url("Edit.js");
                public static readonly string Index_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Index.min.js") ? Url("Index.min.js") : Url("Index.js");
            }
        
        }
    
        public static readonly string MicrosoftAjax_debug_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/MicrosoftAjax.debug.min.js") ? Url("MicrosoftAjax.debug.min.js") : Url("MicrosoftAjax.debug.js");
        public static readonly string MicrosoftAjax_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/MicrosoftAjax.min.js") ? Url("MicrosoftAjax.min.js") : Url("MicrosoftAjax.js");
        public static readonly string MicrosoftMvcAjax_debug_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/MicrosoftMvcAjax.debug.min.js") ? Url("MicrosoftMvcAjax.debug.min.js") : Url("MicrosoftMvcAjax.debug.js");
        public static readonly string MicrosoftMvcAjax_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/MicrosoftMvcAjax.min.js") ? Url("MicrosoftMvcAjax.min.js") : Url("MicrosoftMvcAjax.js");
        public static readonly string MicrosoftMvcValidation_debug_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/MicrosoftMvcValidation.debug.min.js") ? Url("MicrosoftMvcValidation.debug.min.js") : Url("MicrosoftMvcValidation.debug.js");
        public static readonly string MicrosoftMvcValidation_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/MicrosoftMvcValidation.min.js") ? Url("MicrosoftMvcValidation.min.js") : Url("MicrosoftMvcValidation.js");
        public static readonly string modernizr_1_7_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/modernizr-1.7.min.js") ? Url("modernizr-1.7.min.js") : Url("modernizr-1.7.js");
        public static readonly string modernizr_1_7_min_js = Url("modernizr-1.7.min.js");
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Content {
        private const string URLPATH = "~/Content";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        public static readonly string bootstrap_theme_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap-theme.min.css") ? Url("bootstrap-theme.min.css") : Url("bootstrap-theme.css");
             
        public static readonly string bootstrap_theme_css_map = Url("bootstrap-theme.css.map");
        public static readonly string bootstrap_theme_min_css = Url("bootstrap-theme.min.css");
        public static readonly string bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap.min.css") ? Url("bootstrap.min.css") : Url("bootstrap.css");
             
        public static readonly string bootstrap_css_map = Url("bootstrap.css.map");
        public static readonly string bootstrap_min_css = Url("bootstrap.min.css");
        public static readonly string Common_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Common.min.css") ? Url("Common.min.css") : Url("Common.css");
             
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class kendo {
            private const string URLPATH = "~/Content/kendo";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class _2014_1_318 {
                private const string URLPATH = "~/Content/kendo/2014.1.318";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class Black {
                    private const string URLPATH = "~/Content/kendo/2014.1.318/Black";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string editor_png = Url("editor.png");
                    public static readonly string imagebrowser_png = Url("imagebrowser.png");
                    public static readonly string indeterminate_gif = Url("indeterminate.gif");
                    public static readonly string loading_image_gif = Url("loading-image.gif");
                    public static readonly string loading_gif = Url("loading.gif");
                    public static readonly string loading_2x_gif = Url("loading_2x.gif");
                    public static readonly string markers_png = Url("markers.png");
                    public static readonly string markers_2x_png = Url("markers_2x.png");
                    public static readonly string slider_h_gif = Url("slider-h.gif");
                    public static readonly string slider_v_gif = Url("slider-v.gif");
                    public static readonly string sprite_png = Url("sprite.png");
                    public static readonly string sprite_2x_png = Url("sprite_2x.png");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class BlueOpal {
                    private const string URLPATH = "~/Content/kendo/2014.1.318/BlueOpal";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string editor_png = Url("editor.png");
                    public static readonly string imagebrowser_png = Url("imagebrowser.png");
                    public static readonly string indeterminate_gif = Url("indeterminate.gif");
                    public static readonly string loading_image_gif = Url("loading-image.gif");
                    public static readonly string loading_gif = Url("loading.gif");
                    public static readonly string loading_2x_gif = Url("loading_2x.gif");
                    public static readonly string markers_png = Url("markers.png");
                    public static readonly string markers_2x_png = Url("markers_2x.png");
                    public static readonly string slider_h_gif = Url("slider-h.gif");
                    public static readonly string slider_v_gif = Url("slider-v.gif");
                    public static readonly string sprite_png = Url("sprite.png");
                    public static readonly string sprite_2x_png = Url("sprite_2x.png");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class Bootstrap {
                    private const string URLPATH = "~/Content/kendo/2014.1.318/Bootstrap";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string editor_png = Url("editor.png");
                    public static readonly string imagebrowser_png = Url("imagebrowser.png");
                    public static readonly string indeterminate_gif = Url("indeterminate.gif");
                    public static readonly string loading_image_gif = Url("loading-image.gif");
                    public static readonly string loading_gif = Url("loading.gif");
                    public static readonly string loading_2x_gif = Url("loading_2x.gif");
                    public static readonly string markers_png = Url("markers.png");
                    public static readonly string markers_2x_png = Url("markers_2x.png");
                    public static readonly string slider_h_gif = Url("slider-h.gif");
                    public static readonly string slider_v_gif = Url("slider-v.gif");
                    public static readonly string sprite_png = Url("sprite.png");
                    public static readonly string sprite_2x_png = Url("sprite_2x.png");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class Default {
                    private const string URLPATH = "~/Content/kendo/2014.1.318/Default";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string editor_png = Url("editor.png");
                    public static readonly string imagebrowser_png = Url("imagebrowser.png");
                    public static readonly string indeterminate_gif = Url("indeterminate.gif");
                    public static readonly string loading_image_gif = Url("loading-image.gif");
                    public static readonly string loading_gif = Url("loading.gif");
                    public static readonly string loading_2x_gif = Url("loading_2x.gif");
                    public static readonly string markers_png = Url("markers.png");
                    public static readonly string markers_2x_png = Url("markers_2x.png");
                    public static readonly string slider_h_gif = Url("slider-h.gif");
                    public static readonly string slider_v_gif = Url("slider-v.gif");
                    public static readonly string sprite_png = Url("sprite.png");
                    public static readonly string sprite_2x_png = Url("sprite_2x.png");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class Flat {
                    private const string URLPATH = "~/Content/kendo/2014.1.318/Flat";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string editor_png = Url("editor.png");
                    public static readonly string imagebrowser_png = Url("imagebrowser.png");
                    public static readonly string indeterminate_gif = Url("indeterminate.gif");
                    public static readonly string loading_image_gif = Url("loading-image.gif");
                    public static readonly string loading_gif = Url("loading.gif");
                    public static readonly string loading_2x_gif = Url("loading_2x.gif");
                    public static readonly string markers_png = Url("markers.png");
                    public static readonly string markers_2x_png = Url("markers_2x.png");
                    public static readonly string slider_h_gif = Url("slider-h.gif");
                    public static readonly string slider_v_gif = Url("slider-v.gif");
                    public static readonly string sprite_png = Url("sprite.png");
                    public static readonly string sprite_2x_png = Url("sprite_2x.png");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class HighContrast {
                    private const string URLPATH = "~/Content/kendo/2014.1.318/HighContrast";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string editor_png = Url("editor.png");
                    public static readonly string imagebrowser_png = Url("imagebrowser.png");
                    public static readonly string indeterminate_gif = Url("indeterminate.gif");
                    public static readonly string loading_image_gif = Url("loading-image.gif");
                    public static readonly string loading_gif = Url("loading.gif");
                    public static readonly string loading_2x_gif = Url("loading_2x.gif");
                    public static readonly string markers_png = Url("markers.png");
                    public static readonly string markers_2x_png = Url("markers_2x.png");
                    public static readonly string slider_h_gif = Url("slider-h.gif");
                    public static readonly string slider_v_gif = Url("slider-v.gif");
                    public static readonly string sprite_png = Url("sprite.png");
                    public static readonly string sprite_2x_png = Url("sprite_2x.png");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class images {
                    private const string URLPATH = "~/Content/kendo/2014.1.318/images";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string back_png = Url("back.png");
                    public static readonly string wp8_icons_png = Url("wp8_icons.png");
                    public static readonly string wp8_inverseicons_png = Url("wp8_inverseicons.png");
                }
            
                public static readonly string kendo_black_min_css = Url("kendo.black.min.css");
                public static readonly string kendo_black_mobile_min_css = Url("kendo.black.mobile.min.css");
                public static readonly string kendo_blueopal_min_css = Url("kendo.blueopal.min.css");
                public static readonly string kendo_blueopal_mobile_min_css = Url("kendo.blueopal.mobile.min.css");
                public static readonly string kendo_bootstrap_min_css = Url("kendo.bootstrap.min.css");
                public static readonly string kendo_bootstrap_mobile_min_css = Url("kendo.bootstrap.mobile.min.css");
                public static readonly string kendo_common_bootstrap_core_min_css = Url("kendo.common-bootstrap.core.min.css");
                public static readonly string kendo_common_bootstrap_min_css = Url("kendo.common-bootstrap.min.css");
                public static readonly string kendo_common_core_min_css = Url("kendo.common.core.min.css");
                public static readonly string kendo_common_min_css = Url("kendo.common.min.css");
                public static readonly string kendo_dataviz_black_min_css = Url("kendo.dataviz.black.min.css");
                public static readonly string kendo_dataviz_blueopal_min_css = Url("kendo.dataviz.blueopal.min.css");
                public static readonly string kendo_dataviz_bootstrap_min_css = Url("kendo.dataviz.bootstrap.min.css");
                public static readonly string kendo_dataviz_default_min_css = Url("kendo.dataviz.default.min.css");
                public static readonly string kendo_dataviz_flat_min_css = Url("kendo.dataviz.flat.min.css");
                public static readonly string kendo_dataviz_highcontrast_min_css = Url("kendo.dataviz.highcontrast.min.css");
                public static readonly string kendo_dataviz_metro_min_css = Url("kendo.dataviz.metro.min.css");
                public static readonly string kendo_dataviz_metroblack_min_css = Url("kendo.dataviz.metroblack.min.css");
                public static readonly string kendo_dataviz_min_css = Url("kendo.dataviz.min.css");
                public static readonly string kendo_dataviz_moonlight_min_css = Url("kendo.dataviz.moonlight.min.css");
                public static readonly string kendo_dataviz_silver_min_css = Url("kendo.dataviz.silver.min.css");
                public static readonly string kendo_dataviz_uniform_min_css = Url("kendo.dataviz.uniform.min.css");
                public static readonly string kendo_default_min_css = Url("kendo.default.min.css");
                public static readonly string kendo_default_mobile_min_css = Url("kendo.default.mobile.min.css");
                public static readonly string kendo_flat_min_css = Url("kendo.flat.min.css");
                public static readonly string kendo_flat_mobile_min_css = Url("kendo.flat.mobile.min.css");
                public static readonly string kendo_highcontrast_min_css = Url("kendo.highcontrast.min.css");
                public static readonly string kendo_highcontrast_mobile_min_css = Url("kendo.highcontrast.mobile.min.css");
                public static readonly string kendo_metro_min_css = Url("kendo.metro.min.css");
                public static readonly string kendo_metro_mobile_min_css = Url("kendo.metro.mobile.min.css");
                public static readonly string kendo_metroblack_min_css = Url("kendo.metroblack.min.css");
                public static readonly string kendo_metroblack_mobile_min_css = Url("kendo.metroblack.mobile.min.css");
                public static readonly string kendo_mobile_all_min_css = Url("kendo.mobile.all.min.css");
                public static readonly string kendo_mobile_android_dark_min_css = Url("kendo.mobile.android.dark.min.css");
                public static readonly string kendo_mobile_android_light_min_css = Url("kendo.mobile.android.light.min.css");
                public static readonly string kendo_mobile_blackberry_min_css = Url("kendo.mobile.blackberry.min.css");
                public static readonly string kendo_mobile_common_min_css = Url("kendo.mobile.common.min.css");
                public static readonly string kendo_mobile_flat_min_css = Url("kendo.mobile.flat.min.css");
                public static readonly string kendo_mobile_icenium_min_css = Url("kendo.mobile.icenium.min.css");
                public static readonly string kendo_mobile_ios_min_css = Url("kendo.mobile.ios.min.css");
                public static readonly string kendo_mobile_meego_min_css = Url("kendo.mobile.meego.min.css");
                public static readonly string kendo_mobile_wp8_min_css = Url("kendo.mobile.wp8.min.css");
                public static readonly string kendo_moonlight_min_css = Url("kendo.moonlight.min.css");
                public static readonly string kendo_moonlight_mobile_min_css = Url("kendo.moonlight.mobile.min.css");
                public static readonly string kendo_rtl_min_css = Url("kendo.rtl.min.css");
                public static readonly string kendo_silver_min_css = Url("kendo.silver.min.css");
                public static readonly string kendo_silver_mobile_min_css = Url("kendo.silver.mobile.min.css");
                public static readonly string kendo_uniform_min_css = Url("kendo.uniform.min.css");
                public static readonly string kendo_uniform_mobile_min_css = Url("kendo.uniform.mobile.min.css");
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class Metro {
                    private const string URLPATH = "~/Content/kendo/2014.1.318/Metro";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string editor_png = Url("editor.png");
                    public static readonly string imagebrowser_png = Url("imagebrowser.png");
                    public static readonly string indeterminate_gif = Url("indeterminate.gif");
                    public static readonly string loading_image_gif = Url("loading-image.gif");
                    public static readonly string loading_gif = Url("loading.gif");
                    public static readonly string loading_2x_gif = Url("loading_2x.gif");
                    public static readonly string markers_png = Url("markers.png");
                    public static readonly string markers_2x_png = Url("markers_2x.png");
                    public static readonly string slider_h_gif = Url("slider-h.gif");
                    public static readonly string slider_v_gif = Url("slider-v.gif");
                    public static readonly string sprite_png = Url("sprite.png");
                    public static readonly string sprite_2x_png = Url("sprite_2x.png");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class MetroBlack {
                    private const string URLPATH = "~/Content/kendo/2014.1.318/MetroBlack";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string editor_png = Url("editor.png");
                    public static readonly string imagebrowser_png = Url("imagebrowser.png");
                    public static readonly string indeterminate_gif = Url("indeterminate.gif");
                    public static readonly string loading_image_gif = Url("loading-image.gif");
                    public static readonly string loading_gif = Url("loading.gif");
                    public static readonly string loading_2x_gif = Url("loading_2x.gif");
                    public static readonly string markers_png = Url("markers.png");
                    public static readonly string markers_2x_png = Url("markers_2x.png");
                    public static readonly string slider_h_gif = Url("slider-h.gif");
                    public static readonly string slider_v_gif = Url("slider-v.gif");
                    public static readonly string sprite_png = Url("sprite.png");
                    public static readonly string sprite_2x_png = Url("sprite_2x.png");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class Moonlight {
                    private const string URLPATH = "~/Content/kendo/2014.1.318/Moonlight";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string editor_png = Url("editor.png");
                    public static readonly string imagebrowser_png = Url("imagebrowser.png");
                    public static readonly string indeterminate_gif = Url("indeterminate.gif");
                    public static readonly string loading_image_gif = Url("loading-image.gif");
                    public static readonly string loading_gif = Url("loading.gif");
                    public static readonly string loading_2x_gif = Url("loading_2x.gif");
                    public static readonly string markers_png = Url("markers.png");
                    public static readonly string markers_2x_png = Url("markers_2x.png");
                    public static readonly string slider_h_gif = Url("slider-h.gif");
                    public static readonly string slider_v_gif = Url("slider-v.gif");
                    public static readonly string sprite_png = Url("sprite.png");
                    public static readonly string sprite_2x_png = Url("sprite_2x.png");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class Silver {
                    private const string URLPATH = "~/Content/kendo/2014.1.318/Silver";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string editor_png = Url("editor.png");
                    public static readonly string imagebrowser_png = Url("imagebrowser.png");
                    public static readonly string indeterminate_gif = Url("indeterminate.gif");
                    public static readonly string loading_image_gif = Url("loading-image.gif");
                    public static readonly string loading_gif = Url("loading.gif");
                    public static readonly string loading_2x_gif = Url("loading_2x.gif");
                    public static readonly string markers_png = Url("markers.png");
                    public static readonly string markers_2x_png = Url("markers_2x.png");
                    public static readonly string slider_h_gif = Url("slider-h.gif");
                    public static readonly string slider_v_gif = Url("slider-v.gif");
                    public static readonly string sprite_png = Url("sprite.png");
                    public static readonly string sprite_2x_png = Url("sprite_2x.png");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class textures {
                    private const string URLPATH = "~/Content/kendo/2014.1.318/textures";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string brushed_metal_png = Url("brushed-metal.png");
                    public static readonly string dots1_png = Url("dots1.png");
                    public static readonly string dots10_png = Url("dots10.png");
                    public static readonly string dots11_png = Url("dots11.png");
                    public static readonly string dots12_png = Url("dots12.png");
                    public static readonly string dots13_png = Url("dots13.png");
                    public static readonly string dots2_png = Url("dots2.png");
                    public static readonly string dots3_png = Url("dots3.png");
                    public static readonly string dots4_png = Url("dots4.png");
                    public static readonly string dots5_png = Url("dots5.png");
                    public static readonly string dots6_png = Url("dots6.png");
                    public static readonly string dots7_png = Url("dots7.png");
                    public static readonly string dots8_png = Url("dots8.png");
                    public static readonly string dots9_png = Url("dots9.png");
                    public static readonly string glass_lighter_png = Url("glass-lighter.png");
                    public static readonly string glass_png = Url("glass.png");
                    public static readonly string highlight_png = Url("highlight.png");
                    public static readonly string hsv_gradient_png = Url("hsv-gradient.png");
                    public static readonly string hue_png = Url("hue.png");
                    public static readonly string leather1_png = Url("leather1.png");
                    public static readonly string leather2_png = Url("leather2.png");
                    public static readonly string noise_png = Url("noise.png");
                    public static readonly string stripe1_png = Url("stripe1.png");
                    public static readonly string stripe2_png = Url("stripe2.png");
                    public static readonly string stripe3_png = Url("stripe3.png");
                    public static readonly string stripe4_png = Url("stripe4.png");
                    public static readonly string stripe5_png = Url("stripe5.png");
                    public static readonly string stripe6_png = Url("stripe6.png");
                    public static readonly string transparency_png = Url("transparency.png");
                    public static readonly string transtexture_png = Url("transtexture.png");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class Uniform {
                    private const string URLPATH = "~/Content/kendo/2014.1.318/Uniform";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string editor_png = Url("editor.png");
                    public static readonly string imagebrowser_png = Url("imagebrowser.png");
                    public static readonly string indeterminate_gif = Url("indeterminate.gif");
                    public static readonly string loading_image_gif = Url("loading-image.gif");
                    public static readonly string loading_gif = Url("loading.gif");
                    public static readonly string loading_2x_gif = Url("loading_2x.gif");
                    public static readonly string markers_png = Url("markers.png");
                    public static readonly string markers_2x_png = Url("markers_2x.png");
                    public static readonly string slider_h_gif = Url("slider-h.gif");
                    public static readonly string slider_v_gif = Url("slider-v.gif");
                    public static readonly string sprite_png = Url("sprite.png");
                    public static readonly string sprite_2x_png = Url("sprite_2x.png");
                }
            
            }
        
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class themes {
            private const string URLPATH = "~/Content/themes";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class @base {
                private const string URLPATH = "~/Content/themes/base";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class images {
                    private const string URLPATH = "~/Content/themes/base/images";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string ui_bg_flat_0_aaaaaa_40x100_png = Url("ui-bg_flat_0_aaaaaa_40x100.png");
                    public static readonly string ui_bg_flat_75_ffffff_40x100_png = Url("ui-bg_flat_75_ffffff_40x100.png");
                    public static readonly string ui_bg_glass_55_fbf9ee_1x400_png = Url("ui-bg_glass_55_fbf9ee_1x400.png");
                    public static readonly string ui_bg_glass_65_ffffff_1x400_png = Url("ui-bg_glass_65_ffffff_1x400.png");
                    public static readonly string ui_bg_glass_75_dadada_1x400_png = Url("ui-bg_glass_75_dadada_1x400.png");
                    public static readonly string ui_bg_glass_75_e6e6e6_1x400_png = Url("ui-bg_glass_75_e6e6e6_1x400.png");
                    public static readonly string ui_bg_glass_95_fef1ec_1x400_png = Url("ui-bg_glass_95_fef1ec_1x400.png");
                    public static readonly string ui_bg_highlight_soft_75_cccccc_1x100_png = Url("ui-bg_highlight-soft_75_cccccc_1x100.png");
                    public static readonly string ui_icons_222222_256x240_png = Url("ui-icons_222222_256x240.png");
                    public static readonly string ui_icons_2e83ff_256x240_png = Url("ui-icons_2e83ff_256x240.png");
                    public static readonly string ui_icons_454545_256x240_png = Url("ui-icons_454545_256x240.png");
                    public static readonly string ui_icons_888888_256x240_png = Url("ui-icons_888888_256x240.png");
                    public static readonly string ui_icons_cd0a0a_256x240_png = Url("ui-icons_cd0a0a_256x240.png");
                }
            
                public static readonly string jquery_ui_accordion_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.accordion.min.css") ? Url("jquery.ui.accordion.min.css") : Url("jquery.ui.accordion.css");
                     
                public static readonly string jquery_ui_all_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.all.min.css") ? Url("jquery.ui.all.min.css") : Url("jquery.ui.all.css");
                     
                public static readonly string jquery_ui_autocomplete_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.autocomplete.min.css") ? Url("jquery.ui.autocomplete.min.css") : Url("jquery.ui.autocomplete.css");
                     
                public static readonly string jquery_ui_base_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.base.min.css") ? Url("jquery.ui.base.min.css") : Url("jquery.ui.base.css");
                     
                public static readonly string jquery_ui_button_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.button.min.css") ? Url("jquery.ui.button.min.css") : Url("jquery.ui.button.css");
                     
                public static readonly string jquery_ui_core_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.core.min.css") ? Url("jquery.ui.core.min.css") : Url("jquery.ui.core.css");
                     
                public static readonly string jquery_ui_datepicker_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.datepicker.min.css") ? Url("jquery.ui.datepicker.min.css") : Url("jquery.ui.datepicker.css");
                     
                public static readonly string jquery_ui_dialog_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.dialog.min.css") ? Url("jquery.ui.dialog.min.css") : Url("jquery.ui.dialog.css");
                     
                public static readonly string jquery_ui_progressbar_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.progressbar.min.css") ? Url("jquery.ui.progressbar.min.css") : Url("jquery.ui.progressbar.css");
                     
                public static readonly string jquery_ui_resizable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.resizable.min.css") ? Url("jquery.ui.resizable.min.css") : Url("jquery.ui.resizable.css");
                     
                public static readonly string jquery_ui_selectable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.selectable.min.css") ? Url("jquery.ui.selectable.min.css") : Url("jquery.ui.selectable.css");
                     
                public static readonly string jquery_ui_slider_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.slider.min.css") ? Url("jquery.ui.slider.min.css") : Url("jquery.ui.slider.css");
                     
                public static readonly string jquery_ui_tabs_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.tabs.min.css") ? Url("jquery.ui.tabs.min.css") : Url("jquery.ui.tabs.css");
                     
                public static readonly string jquery_ui_theme_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.theme.min.css") ? Url("jquery.ui.theme.min.css") : Url("jquery.ui.theme.css");
                     
            }
        
        }
    
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Bundles
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static partial class Scripts {}
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static partial class Styles {}
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        string path = VirtualPathUtility.ToAbsolute(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;

    // Calling T4Extension.TimestampString through delegate to allow it to be replaced for unit testing and other purposes
    public static Func<string, string> TimestampString = System.Web.Mvc.T4Extensions.TimestampString;

    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}





#endregion T4MVC
#pragma warning restore 1591


